language: rust

rust: stable

os:
  - linux
  - osx
  - windows

cache: cargo

script:
  - cargo test --verbose

_deploy_settings: &deploy_settings
  script:
    - cargo build --release
  before_deploy:
    - mv "target/release/$EXE_FILE" .
    - tar -zcvf "$DEPLOY_FILE" "$EXE_FILE"
  deploy:
    provider: releases
    file: "$DEPLOY_FILE"

    api_key: $GITHUB_API_KEY

    on:
      repo: andreivasiliu/nlua

    draft: true
    skip_cleanup: true

jobs:
  include:
    - stage: deploy
      name: deploy linux
      os: linux
      env: EXE_FILE="nlua" DEPLOY_FILE="nlua-${TRAVIS_OS_NAME}.tar.gz"
      <<: *deploy_settings
    - stage: deploy
      name: deploy osx
      os: osx
      env: EXE_FILE="nlua" DEPLOY_FILE="nlua-${TRAVIS_OS_NAME}.tar.gz"
      <<: *deploy_settings
    - stage: deploy
      name: deploy windows
      os: windows
      env: EXE_FILE="nlua.exe" DEPLOY_FILE="nlua-${TRAVIS_OS_NAME}.tar.gz"
      <<: *deploy_settings
